[package]
authors = ["Alyssa <alyssarosedev@protonmail.com>"]
edition = "2021"
name = "transcriptase"
version = "0.1.0"

[dependencies]
nom = "7.1.1"
nom-supreme = "0.8.0"
thiserror = "1.0.31"
tracing = "0.1.34"
